//
// Created by marco on 05/04/18.
//

#ifndef CFACTORIAL_IDE_REQUESTTYPES_H
#define CFACTORIAL_IDE_REQUESTTYPES_H

enum RequestTypes{

    NEW_VARIABLE,
    NEW_STRUCT,
    GET_VARIABLE,
    GET_STRUCT,
    GET_ADDRESS,
    GARBAGE_COLLECTOR

};


#endif //CFACTORIAL_IDE_REQUESTTYPES_H